name = "edge-chat-demo"
type = "javascript"
workers_dev = true
# Add your account ID here
account_id = "2ccb840de076261467812cbc32f8aa47"

[build.upload]
format = "modules"
dir = "src"
main = "./chat.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]
